/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TemplateId = IDL.Nat;
export const PostId = IDL.Nat;
export const ListingId = IDL.Nat;
export const PlanType = IDL.Variant({
  'pro' : IDL.Null,
  'creator' : IDL.Null,
  'free' : IDL.Null,
});
export const SubscriptionState = IDL.Variant({
  'active' : IDL.Null,
  'canceled' : IDL.Null,
  'expired' : IDL.Null,
});
export const Subscription = IDL.Record({
  'status' : SubscriptionState,
  'premiumUntil' : IDL.Opt(IDL.Int),
  'userId' : IDL.Principal,
  'plan' : PlanType,
});
export const CommunityPost = IDL.Record({
  'id' : PostId,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'contentType' : IDL.Variant({ 'template' : TemplateId, 'sticker' : IDL.Nat }),
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
});
export const MarketplaceListing = IDL.Record({
  'id' : ListingId,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'contentType' : IDL.Variant({ 'template' : TemplateId, 'sticker' : IDL.Nat }),
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PaymentRequest = IDL.Record({
  'id' : IDL.Text,
  'utr' : IDL.Text,
  'status' : PaymentStatus,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'plan' : PlanType,
  'reviewedAt' : IDL.Opt(IDL.Int),
  'email' : IDL.Text,
  'amount' : IDL.Nat,
  'screenshot' : IDL.Opt(ExternalBlob),
});
export const DownloadRecord = IDL.Record({
  'contentId' : IDL.Nat,
  'contentType' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const SavedTemplate = IDL.Record({
  'templateId' : IDL.Nat,
  'savedAt' : IDL.Int,
});
export const SubscriptionStatus = IDL.Record({
  'startedAt' : IDL.Int,
  'expiresAt' : IDL.Opt(IDL.Int),
  'plan' : PlanType,
  'updatedAt' : IDL.Int,
  'state' : SubscriptionState,
});
export const UserProfile = IDL.Record({ 'bio' : IDL.Text, 'name' : IDL.Text });
export const CreatorEarnings = IDL.Record({
  'totalRevenue' : IDL.Nat,
  'totalDownloads' : IDL.Nat,
});
export const SurprisePayload = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'message' : IDL.Text,
  'recipientName' : IDL.Text,
});
export const UserAuth = IDL.Record({
  'provider' : IDL.Text,
  'lastLoginAt' : IDL.Int,
  'createdAt' : IDL.Int,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addScreenshotToPayment' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCommunityPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Variant({ 'template' : TemplateId, 'sticker' : IDL.Nat }),
      ],
      [PostId],
      [],
    ),
  'createMarketplaceListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Variant({ 'template' : TemplateId, 'sticker' : IDL.Nat }),
      ],
      [ListingId],
      [],
    ),
  'createOrUpdateUserAuth' : IDL.Func([IDL.Text], [], []),
  'createPaymentRequest' : IDL.Func(
      [IDL.Text, PlanType, IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Text],
      [],
    ),
  'createSubscription' : IDL.Func(
      [IDL.Principal, PlanType, SubscriptionState],
      [],
      [],
    ),
  'createSurpriseLink' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getAllActiveSubscriptions' : IDL.Func(
      [],
      [IDL.Vec(Subscription)],
      ['query'],
    ),
  'getAllCommunityPosts' : IDL.Func([], [IDL.Vec(CommunityPost)], ['query']),
  'getAllMarketplaceListings' : IDL.Func(
      [],
      [IDL.Vec(MarketplaceListing)],
      ['query'],
    ),
  'getAllPaymentRequests' : IDL.Func([], [IDL.Vec(PaymentRequest)], ['query']),
  'getCallerDownloadHistory' : IDL.Func(
      [],
      [IDL.Vec(DownloadRecord)],
      ['query'],
    ),
  'getCallerSavedTemplates' : IDL.Func([], [IDL.Vec(SavedTemplate)], ['query']),
  'getCallerSubscriptionStatus' : IDL.Func([], [SubscriptionStatus], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommunityPost' : IDL.Func([PostId], [IDL.Opt(CommunityPost)], ['query']),
  'getCreatorEarnings' : IDL.Func([], [CreatorEarnings], ['query']),
  'getCreatorListings' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(MarketplaceListing)],
      ['query'],
    ),
  'getCreatorPosts' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CommunityPost)],
      ['query'],
    ),
  'getCreatorSubscribers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getListingInteractionCount' : IDL.Func([ListingId], [IDL.Nat], ['query']),
  'getMarketplaceListing' : IDL.Func(
      [ListingId],
      [IDL.Opt(MarketplaceListing)],
      ['query'],
    ),
  'getMessageQuotaStatus' : IDL.Func(
      [],
      [IDL.Record({ 'total' : IDL.Nat, 'remaining' : IDL.Nat })],
      ['query'],
    ),
  'getPaymentRequest' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PaymentRequest)],
      ['query'],
    ),
  'getSurprisePayload' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SurprisePayload)],
      ['query'],
    ),
  'getUserAuth' : IDL.Func([], [IDL.Opt(UserAuth)], ['query']),
  'getUserPaymentRequests' : IDL.Func([], [IDL.Vec(PaymentRequest)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordDownload' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'recordListingInteraction' : IDL.Func([ListingId], [], []),
  'recordMessageGeneration' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveTemplate' : IDL.Func([IDL.Nat], [], []),
  'subscribeToCreator' : IDL.Func([IDL.Principal], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updatePaymentRequestStatus' : IDL.Func([IDL.Text, PaymentStatus], [], []),
  'updatePaymentStatus' : IDL.Func([IDL.Text, PaymentStatus], [], []),
  'updateSubscriptionStatus' : IDL.Func(
      [IDL.Principal, PlanType, SubscriptionState, IDL.Opt(IDL.Int)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TemplateId = IDL.Nat;
  const PostId = IDL.Nat;
  const ListingId = IDL.Nat;
  const PlanType = IDL.Variant({
    'pro' : IDL.Null,
    'creator' : IDL.Null,
    'free' : IDL.Null,
  });
  const SubscriptionState = IDL.Variant({
    'active' : IDL.Null,
    'canceled' : IDL.Null,
    'expired' : IDL.Null,
  });
  const Subscription = IDL.Record({
    'status' : SubscriptionState,
    'premiumUntil' : IDL.Opt(IDL.Int),
    'userId' : IDL.Principal,
    'plan' : PlanType,
  });
  const CommunityPost = IDL.Record({
    'id' : PostId,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'contentType' : IDL.Variant({
      'template' : TemplateId,
      'sticker' : IDL.Nat,
    }),
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
  });
  const MarketplaceListing = IDL.Record({
    'id' : ListingId,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'contentType' : IDL.Variant({
      'template' : TemplateId,
      'sticker' : IDL.Nat,
    }),
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PaymentRequest = IDL.Record({
    'id' : IDL.Text,
    'utr' : IDL.Text,
    'status' : PaymentStatus,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'plan' : PlanType,
    'reviewedAt' : IDL.Opt(IDL.Int),
    'email' : IDL.Text,
    'amount' : IDL.Nat,
    'screenshot' : IDL.Opt(ExternalBlob),
  });
  const DownloadRecord = IDL.Record({
    'contentId' : IDL.Nat,
    'contentType' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const SavedTemplate = IDL.Record({
    'templateId' : IDL.Nat,
    'savedAt' : IDL.Int,
  });
  const SubscriptionStatus = IDL.Record({
    'startedAt' : IDL.Int,
    'expiresAt' : IDL.Opt(IDL.Int),
    'plan' : PlanType,
    'updatedAt' : IDL.Int,
    'state' : SubscriptionState,
  });
  const UserProfile = IDL.Record({ 'bio' : IDL.Text, 'name' : IDL.Text });
  const CreatorEarnings = IDL.Record({
    'totalRevenue' : IDL.Nat,
    'totalDownloads' : IDL.Nat,
  });
  const SurprisePayload = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'message' : IDL.Text,
    'recipientName' : IDL.Text,
  });
  const UserAuth = IDL.Record({
    'provider' : IDL.Text,
    'lastLoginAt' : IDL.Int,
    'createdAt' : IDL.Int,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addScreenshotToPayment' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCommunityPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Variant({ 'template' : TemplateId, 'sticker' : IDL.Nat }),
        ],
        [PostId],
        [],
      ),
    'createMarketplaceListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Variant({ 'template' : TemplateId, 'sticker' : IDL.Nat }),
        ],
        [ListingId],
        [],
      ),
    'createOrUpdateUserAuth' : IDL.Func([IDL.Text], [], []),
    'createPaymentRequest' : IDL.Func(
        [IDL.Text, PlanType, IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Text],
        [],
      ),
    'createSubscription' : IDL.Func(
        [IDL.Principal, PlanType, SubscriptionState],
        [],
        [],
      ),
    'createSurpriseLink' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getAllActiveSubscriptions' : IDL.Func(
        [],
        [IDL.Vec(Subscription)],
        ['query'],
      ),
    'getAllCommunityPosts' : IDL.Func([], [IDL.Vec(CommunityPost)], ['query']),
    'getAllMarketplaceListings' : IDL.Func(
        [],
        [IDL.Vec(MarketplaceListing)],
        ['query'],
      ),
    'getAllPaymentRequests' : IDL.Func(
        [],
        [IDL.Vec(PaymentRequest)],
        ['query'],
      ),
    'getCallerDownloadHistory' : IDL.Func(
        [],
        [IDL.Vec(DownloadRecord)],
        ['query'],
      ),
    'getCallerSavedTemplates' : IDL.Func(
        [],
        [IDL.Vec(SavedTemplate)],
        ['query'],
      ),
    'getCallerSubscriptionStatus' : IDL.Func(
        [],
        [SubscriptionStatus],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommunityPost' : IDL.Func(
        [PostId],
        [IDL.Opt(CommunityPost)],
        ['query'],
      ),
    'getCreatorEarnings' : IDL.Func([], [CreatorEarnings], ['query']),
    'getCreatorListings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(MarketplaceListing)],
        ['query'],
      ),
    'getCreatorPosts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CommunityPost)],
        ['query'],
      ),
    'getCreatorSubscribers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getListingInteractionCount' : IDL.Func([ListingId], [IDL.Nat], ['query']),
    'getMarketplaceListing' : IDL.Func(
        [ListingId],
        [IDL.Opt(MarketplaceListing)],
        ['query'],
      ),
    'getMessageQuotaStatus' : IDL.Func(
        [],
        [IDL.Record({ 'total' : IDL.Nat, 'remaining' : IDL.Nat })],
        ['query'],
      ),
    'getPaymentRequest' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PaymentRequest)],
        ['query'],
      ),
    'getSurprisePayload' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SurprisePayload)],
        ['query'],
      ),
    'getUserAuth' : IDL.Func([], [IDL.Opt(UserAuth)], ['query']),
    'getUserPaymentRequests' : IDL.Func(
        [],
        [IDL.Vec(PaymentRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordDownload' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'recordListingInteraction' : IDL.Func([ListingId], [], []),
    'recordMessageGeneration' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveTemplate' : IDL.Func([IDL.Nat], [], []),
    'subscribeToCreator' : IDL.Func([IDL.Principal], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updatePaymentRequestStatus' : IDL.Func([IDL.Text, PaymentStatus], [], []),
    'updatePaymentStatus' : IDL.Func([IDL.Text, PaymentStatus], [], []),
    'updateSubscriptionStatus' : IDL.Func(
        [IDL.Principal, PlanType, SubscriptionState, IDL.Opt(IDL.Int)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };