/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CommunityPost {
  'id' : PostId,
  'title' : string,
  'creator' : Principal,
  'contentType' : { 'template' : TemplateId } |
    { 'sticker' : bigint },
  'createdAt' : bigint,
  'description' : string,
}
export interface CreatorEarnings {
  'totalRevenue' : bigint,
  'totalDownloads' : bigint,
}
export interface DownloadRecord {
  'contentId' : bigint,
  'contentType' : string,
  'timestamp' : bigint,
}
export type ListingId = bigint;
export interface MarketplaceListing {
  'id' : ListingId,
  'title' : string,
  'creator' : Principal,
  'contentType' : { 'template' : TemplateId } |
    { 'sticker' : bigint },
  'createdAt' : bigint,
  'description' : string,
  'price' : bigint,
}
export type PlanType = { 'pro' : null } |
  { 'creator' : null } |
  { 'free' : null };
export type PostId = bigint;
export interface SavedTemplate { 'templateId' : bigint, 'savedAt' : bigint }
export type SubscriptionState = { 'active' : null } |
  { 'canceled' : null } |
  { 'expired' : null };
export interface SubscriptionStatus {
  'startedAt' : bigint,
  'expiresAt' : [] | [bigint],
  'plan' : PlanType,
  'updatedAt' : bigint,
  'state' : SubscriptionState,
}
export interface SurprisePayload {
  'id' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'message' : string,
  'recipientName' : string,
}
export type TemplateId = bigint;
export interface UserProfile { 'bio' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCommunityPost' : ActorMethod<
    [string, string, { 'template' : TemplateId } | { 'sticker' : bigint }],
    PostId
  >,
  'createMarketplaceListing' : ActorMethod<
    [
      string,
      string,
      bigint,
      { 'template' : TemplateId } |
        { 'sticker' : bigint },
    ],
    ListingId
  >,
  'createSurpriseLink' : ActorMethod<[string, string], string>,
  'getAllCommunityPosts' : ActorMethod<[], Array<CommunityPost>>,
  'getAllMarketplaceListings' : ActorMethod<[], Array<MarketplaceListing>>,
  'getCallerDownloadHistory' : ActorMethod<[], Array<DownloadRecord>>,
  'getCallerSavedTemplates' : ActorMethod<[], Array<SavedTemplate>>,
  'getCallerSubscriptionStatus' : ActorMethod<[], SubscriptionStatus>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommunityPost' : ActorMethod<[PostId], [] | [CommunityPost]>,
  'getCreatorEarnings' : ActorMethod<[], CreatorEarnings>,
  'getCreatorListings' : ActorMethod<[Principal], Array<MarketplaceListing>>,
  'getCreatorPosts' : ActorMethod<[Principal], Array<CommunityPost>>,
  'getCreatorSubscribers' : ActorMethod<[Principal], Array<Principal>>,
  'getListingInteractionCount' : ActorMethod<[ListingId], bigint>,
  'getMarketplaceListing' : ActorMethod<[ListingId], [] | [MarketplaceListing]>,
  'getMessageQuotaStatus' : ActorMethod<
    [],
    { 'total' : bigint, 'remaining' : bigint }
  >,
  'getSurprisePayload' : ActorMethod<[string], [] | [SurprisePayload]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordDownload' : ActorMethod<[string, bigint], undefined>,
  'recordListingInteraction' : ActorMethod<[ListingId], undefined>,
  'recordMessageGeneration' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveTemplate' : ActorMethod<[bigint], undefined>,
  'subscribeToCreator' : ActorMethod<[Principal], undefined>,
  'updateSubscriptionStatus' : ActorMethod<
    [Principal, PlanType, SubscriptionState, [] | [bigint]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];