import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Reveal } from '../components/Reveal';

export function LegalSections() {
  return (
    <section className="section-padding px-4 sm:px-6 lg:px-8 bg-muted/30">
      <div className="section-container max-w-4xl space-y-12">
        {/* Privacy Policy */}
        <Reveal>
          <Card id="privacy" className="bg-card/60 backdrop-blur-sm border-border shadow-card scroll-mt-20">
            <CardHeader>
              <CardTitle className="text-2xl">Privacy Policy</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-sm max-w-none dark:prose-invert">
              <p className="text-muted-foreground">
                Your privacy is important to us. This policy outlines how we collect, use, and protect your personal information.
              </p>
              <h3 className="text-lg font-semibold mt-6">Information We Collect</h3>
              <p className="text-muted-foreground">
                We collect information you provide when using WishMint AI, including names, messages, and account details.
              </p>
              <h3 className="text-lg font-semibold mt-6">How We Use Your Information</h3>
              <p className="text-muted-foreground">
                Your information is used to generate personalized birthday wishes and improve our services. We do not sell your data to third parties.
              </p>
              <h3 className="text-lg font-semibold mt-6">Data Security</h3>
              <p className="text-muted-foreground">
                We implement industry-standard security measures to protect your data stored on the Internet Computer blockchain.
              </p>
            </CardContent>
          </Card>
        </Reveal>

        {/* Terms & Conditions */}
        <Reveal>
          <Card id="terms" className="bg-card/60 backdrop-blur-sm border-border shadow-card scroll-mt-20">
            <CardHeader>
              <CardTitle className="text-2xl">Terms & Conditions</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-sm max-w-none dark:prose-invert">
              <p className="text-muted-foreground">
                By using WishMint AI, you agree to these terms and conditions.
              </p>
              <h3 className="text-lg font-semibold mt-6">Acceptable Use</h3>
              <p className="text-muted-foreground">
                You agree to use WishMint AI for lawful purposes only. Do not use the service to generate harmful, offensive, or inappropriate content.
              </p>
              <h3 className="text-lg font-semibold mt-6">Subscription Plans</h3>
              <p className="text-muted-foreground">
                Subscription plans are billed monthly. You can cancel at any time, and your access will continue until the end of the billing period.
              </p>
              <h3 className="text-lg font-semibold mt-6">Intellectual Property</h3>
              <p className="text-muted-foreground">
                Content generated by WishMint AI is yours to use. However, templates and designs created by other users in the marketplace remain their intellectual property.
              </p>
              <h3 className="text-lg font-semibold mt-6">Limitation of Liability</h3>
              <p className="text-muted-foreground">
                WishMint AI is provided "as is" without warranties. We are not liable for any damages arising from your use of the service.
              </p>
            </CardContent>
          </Card>
        </Reveal>

        {/* Refund Policy */}
        <Reveal>
          <Card id="refund" className="bg-card/60 backdrop-blur-sm border-border shadow-card scroll-mt-20">
            <CardHeader>
              <CardTitle className="text-2xl">Refund Policy</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-sm max-w-none dark:prose-invert">
              <p className="text-muted-foreground">
                We want you to be satisfied with WishMint AI. Here's our refund policy:
              </p>
              <h3 className="text-lg font-semibold mt-6">Subscription Refunds</h3>
              <p className="text-muted-foreground">
                If you're not satisfied with your Pro or Creator subscription, you may request a refund within 7 days of purchase. Contact us with your transaction details.
              </p>
              <h3 className="text-lg font-semibold mt-6">Marketplace Purchases</h3>
              <p className="text-muted-foreground">
                Digital products purchased from the marketplace are generally non-refundable. However, if you experience technical issues preventing you from accessing your purchase, contact us for assistance.
              </p>
              <h3 className="text-lg font-semibold mt-6">How to Request a Refund</h3>
              <p className="text-muted-foreground">
                To request a refund, email us at support@wishmint.ai with your account details and reason for the refund request. We'll process eligible refunds within 5-7 business days.
              </p>
            </CardContent>
          </Card>
        </Reveal>

        {/* Contact */}
        <Reveal>
          <Card id="contact" className="bg-card/60 backdrop-blur-sm border-border shadow-card scroll-mt-20">
            <CardHeader>
              <CardTitle className="text-2xl">Contact Us</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-sm max-w-none dark:prose-invert">
              <p className="text-muted-foreground">
                Have questions or need support? We're here to help!
              </p>
              <h3 className="text-lg font-semibold mt-6">Email</h3>
              <p className="text-muted-foreground">
                support@wishmint.ai
              </p>
              <h3 className="text-lg font-semibold mt-6">Response Time</h3>
              <p className="text-muted-foreground">
                We typically respond to inquiries within 24-48 hours during business days.
              </p>
            </CardContent>
          </Card>
        </Reveal>
      </div>
    </section>
  );
}
