import type { PremiumTheme } from './types';

export const PREMIUM_THEMES: PremiumTheme[] = [
  {
    id: 'cute-pastel',
    name: 'Cute Pastel',
    description: 'Soft pink, lavender, baby blue with cute decorations',
    icon: '🌸',
    backgroundGradient: 'linear-gradient(135deg, #FFB6D9 0%, #D5AAFF 50%, #B4E4FF 100%)',
    backgroundColors: ['#FFB6D9', '#B4E4FF'],
    textColor: '#4A4A4A',
    accentColor: '#FF69B4',
    decorativeEmojis: ['💕', '🌸', '✨', '🦋', '💖', '🌺', '⭐'],
    fontFamily: "'Comic Sans MS', 'Chalkboard SE', cursive",
    borderColor: '#FFB6D9',
    glowColor: 'rgba(255, 182, 217, 0.6)',
  },
  {
    id: 'romantic-love',
    name: 'Romantic Love',
    description: 'Red and rose gradient with floating hearts',
    icon: '❤️',
    backgroundGradient: 'linear-gradient(135deg, #FF0844 0%, #FF6B9D 50%, #FFC0CB 100%)',
    backgroundColors: ['#FF0844', '#FFC0CB'],
    textColor: '#FFFFFF',
    accentColor: '#FFD700',
    decorativeEmojis: ['❤️', '💕', '💖', '💗', '💝', '🌹', '💐'],
    fontFamily: "'Brush Script MT', cursive",
    borderColor: '#FFD700',
    glowColor: 'rgba(255, 8, 68, 0.6)',
  },
  {
    id: 'minimal-luxury',
    name: 'Minimal Luxury',
    description: 'Black and gold premium modern look',
    icon: '✨',
    backgroundGradient: 'linear-gradient(135deg, #1a1a1a 0%, #2d1b4e 50%, #1a1a1a 100%)',
    backgroundColors: ['#1a1a1a', '#2d1b4e'],
    textColor: '#FFD700',
    accentColor: '#FFD700',
    decorativeEmojis: ['✨', '💎', '👑', '⭐', '🌟', '💫', '🔆'],
    fontFamily: "'Helvetica Neue', 'Arial', sans-serif",
    borderColor: '#FFD700',
    glowColor: 'rgba(255, 215, 0, 0.6)',
  },
  {
    id: 'neon-party',
    name: 'Neon Party',
    description: 'Bright neon gradients with glow effects',
    icon: '🎉',
    backgroundGradient: 'linear-gradient(135deg, #FF00FF 0%, #00FFFF 50%, #FFFF00 100%)',
    backgroundColors: ['#FF00FF', '#FFFF00'],
    textColor: '#FFFFFF',
    accentColor: '#00FFFF',
    decorativeEmojis: ['🎉', '🎊', '🎈', '🎆', '✨', '💥', '🌟'],
    fontFamily: "'Impact', 'Arial Black', sans-serif",
    borderColor: '#00FFFF',
    glowColor: 'rgba(0, 255, 255, 0.8)',
  },
  {
    id: 'anime-aesthetic',
    name: 'Anime / Aesthetic',
    description: 'Soft aesthetic gradient with sparkle overlay',
    icon: '🌙',
    backgroundGradient: 'linear-gradient(135deg, #a8edea 0%, #fed6e3 50%, #d4a5ff 100%)',
    backgroundColors: ['#a8edea', '#d4a5ff'],
    textColor: '#4A4A4A',
    accentColor: '#9b59b6',
    decorativeEmojis: ['🌙', '⭐', '✨', '💫', '🌸', '🦋', '🌈'],
    fontFamily: "'Courier New', monospace",
    borderColor: '#9b59b6',
    glowColor: 'rgba(155, 89, 182, 0.6)',
  },
];

export function getThemeById(id: string): PremiumTheme {
  return PREMIUM_THEMES.find(t => t.id === id) || PREMIUM_THEMES[0];
}
