/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserAuth {
    provider: string;
    lastLoginAt: bigint;
    createdAt: bigint;
}
export interface CreatorEarnings {
    totalRevenue: bigint;
    totalDownloads: bigint;
}
export type PostId = bigint;
export type TemplateId = bigint;
export interface DownloadRecord {
    contentId: bigint;
    contentType: string;
    timestamp: bigint;
}
export interface CommunityPost {
    id: PostId;
    title: string;
    creator: Principal;
    contentType: {
        __kind__: "template";
        template: TemplateId;
    } | {
        __kind__: "sticker";
        sticker: bigint;
    };
    createdAt: bigint;
    description: string;
}
export interface SavedTemplate {
    templateId: bigint;
    savedAt: bigint;
}
export interface MarketplaceListing {
    id: ListingId;
    title: string;
    creator: Principal;
    contentType: {
        __kind__: "template";
        template: TemplateId;
    } | {
        __kind__: "sticker";
        sticker: bigint;
    };
    createdAt: bigint;
    description: string;
    price: bigint;
}
export type ListingId = bigint;
export interface SubscriptionStatus {
    startedAt: bigint;
    expiresAt?: bigint;
    plan: PlanType;
    updatedAt: bigint;
    state: SubscriptionState;
}
export interface UserProfile {
    bio: string;
    name: string;
}
export interface SurprisePayload {
    id: string;
    createdAt: bigint;
    createdBy: Principal;
    message: string;
    recipientName: string;
}
export enum PlanType {
    pro = "pro",
    creator = "creator",
    free = "free"
}
export enum SubscriptionState {
    active = "active",
    canceled = "canceled",
    expired = "expired"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCommunityPost(title: string, description: string, contentType: {
        __kind__: "template";
        template: TemplateId;
    } | {
        __kind__: "sticker";
        sticker: bigint;
    }): Promise<PostId>;
    createMarketplaceListing(title: string, description: string, price: bigint, contentType: {
        __kind__: "template";
        template: TemplateId;
    } | {
        __kind__: "sticker";
        sticker: bigint;
    }): Promise<ListingId>;
    createOrUpdateUserAuth(provider: string): Promise<void>;
    createSurpriseLink(recipientName: string, message: string): Promise<string>;
    getAllCommunityPosts(): Promise<Array<CommunityPost>>;
    getAllMarketplaceListings(): Promise<Array<MarketplaceListing>>;
    getCallerDownloadHistory(): Promise<Array<DownloadRecord>>;
    getCallerSavedTemplates(): Promise<Array<SavedTemplate>>;
    getCallerSubscriptionStatus(): Promise<SubscriptionStatus>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCommunityPost(id: PostId): Promise<CommunityPost | null>;
    getCreatorEarnings(): Promise<CreatorEarnings>;
    getCreatorListings(creator: Principal): Promise<Array<MarketplaceListing>>;
    getCreatorPosts(creator: Principal): Promise<Array<CommunityPost>>;
    getCreatorSubscribers(creator: Principal): Promise<Array<Principal>>;
    getListingInteractionCount(listingId: ListingId): Promise<bigint>;
    getMarketplaceListing(id: ListingId): Promise<MarketplaceListing | null>;
    getMessageQuotaStatus(): Promise<{
        total: bigint;
        remaining: bigint;
    }>;
    getSurprisePayload(surpriseId: string): Promise<SurprisePayload | null>;
    getUserAuth(): Promise<UserAuth | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    recordDownload(contentType: string, contentId: bigint): Promise<void>;
    recordListingInteraction(listingId: ListingId): Promise<void>;
    recordMessageGeneration(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveTemplate(templateId: bigint): Promise<void>;
    subscribeToCreator(creator: Principal): Promise<void>;
    updateSubscriptionStatus(user: Principal, plan: PlanType, state: SubscriptionState, expiresAt: bigint | null): Promise<void>;
}
import type { CommunityPost as _CommunityPost, ListingId as _ListingId, MarketplaceListing as _MarketplaceListing, PlanType as _PlanType, PostId as _PostId, SubscriptionState as _SubscriptionState, SubscriptionStatus as _SubscriptionStatus, SurprisePayload as _SurprisePayload, TemplateId as _TemplateId, UserAuth as _UserAuth, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCommunityPost(arg0: string, arg1: string, arg2: {
        __kind__: "template";
        template: TemplateId;
    } | {
        __kind__: "sticker";
        sticker: bigint;
    }): Promise<PostId> {
        if (this.processError) {
            try {
                const result = await this.actor.createCommunityPost(arg0, arg1, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCommunityPost(arg0, arg1, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createMarketplaceListing(arg0: string, arg1: string, arg2: bigint, arg3: {
        __kind__: "template";
        template: TemplateId;
    } | {
        __kind__: "sticker";
        sticker: bigint;
    }): Promise<ListingId> {
        if (this.processError) {
            try {
                const result = await this.actor.createMarketplaceListing(arg0, arg1, arg2, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMarketplaceListing(arg0, arg1, arg2, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createOrUpdateUserAuth(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateUserAuth(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateUserAuth(arg0);
            return result;
        }
    }
    async createSurpriseLink(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createSurpriseLink(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSurpriseLink(arg0, arg1);
            return result;
        }
    }
    async getAllCommunityPosts(): Promise<Array<CommunityPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCommunityPosts();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCommunityPosts();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMarketplaceListings(): Promise<Array<MarketplaceListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMarketplaceListings();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMarketplaceListings();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerDownloadHistory(): Promise<Array<DownloadRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerDownloadHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerDownloadHistory();
            return result;
        }
    }
    async getCallerSavedTemplates(): Promise<Array<SavedTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerSavedTemplates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerSavedTemplates();
            return result;
        }
    }
    async getCallerSubscriptionStatus(): Promise<SubscriptionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerSubscriptionStatus();
                return from_candid_SubscriptionStatus_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerSubscriptionStatus();
            return from_candid_SubscriptionStatus_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommunityPost(arg0: PostId): Promise<CommunityPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommunityPost(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommunityPost(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCreatorEarnings(): Promise<CreatorEarnings> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreatorEarnings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreatorEarnings();
            return result;
        }
    }
    async getCreatorListings(arg0: Principal): Promise<Array<MarketplaceListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreatorListings(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreatorListings(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCreatorPosts(arg0: Principal): Promise<Array<CommunityPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreatorPosts(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreatorPosts(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCreatorSubscribers(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreatorSubscribers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreatorSubscribers(arg0);
            return result;
        }
    }
    async getListingInteractionCount(arg0: ListingId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingInteractionCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingInteractionCount(arg0);
            return result;
        }
    }
    async getMarketplaceListing(arg0: ListingId): Promise<MarketplaceListing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketplaceListing(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketplaceListing(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessageQuotaStatus(): Promise<{
        total: bigint;
        remaining: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessageQuotaStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessageQuotaStatus();
            return result;
        }
    }
    async getSurprisePayload(arg0: string): Promise<SurprisePayload | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSurprisePayload(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSurprisePayload(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserAuth(): Promise<UserAuth | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAuth();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAuth();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordDownload(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordDownload(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordDownload(arg0, arg1);
            return result;
        }
    }
    async recordListingInteraction(arg0: ListingId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordListingInteraction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordListingInteraction(arg0);
            return result;
        }
    }
    async recordMessageGeneration(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordMessageGeneration();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordMessageGeneration();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveTemplate(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTemplate(arg0);
            return result;
        }
    }
    async subscribeToCreator(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribeToCreator(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribeToCreator(arg0);
            return result;
        }
    }
    async updateSubscriptionStatus(arg0: Principal, arg1: PlanType, arg2: SubscriptionState, arg3: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubscriptionStatus(arg0, to_candid_PlanType_n25(this._uploadFile, this._downloadFile, arg1), to_candid_SubscriptionState_n27(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n29(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubscriptionStatus(arg0, to_candid_PlanType_n25(this._uploadFile, this._downloadFile, arg1), to_candid_SubscriptionState_n27(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n29(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_CommunityPost_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommunityPost): CommunityPost {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_MarketplaceListing_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketplaceListing): MarketplaceListing {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_PlanType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlanType): PlanType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionState_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionState): SubscriptionState {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CommunityPost]): CommunityPost | null {
    return value.length === 0 ? null : from_candid_CommunityPost_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MarketplaceListing]): MarketplaceListing | null {
    return value.length === 0 ? null : from_candid_MarketplaceListing_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SurprisePayload]): SurprisePayload | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserAuth]): UserAuth | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ListingId;
    title: string;
    creator: Principal;
    contentType: {
        template: _TemplateId;
    } | {
        sticker: bigint;
    };
    createdAt: bigint;
    description: string;
    price: bigint;
}): {
    id: ListingId;
    title: string;
    creator: Principal;
    contentType: {
        __kind__: "template";
        template: TemplateId;
    } | {
        __kind__: "sticker";
        sticker: bigint;
    };
    createdAt: bigint;
    description: string;
    price: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        creator: value.creator,
        contentType: from_candid_variant_n7(_uploadFile, _downloadFile, value.contentType),
        createdAt: value.createdAt,
        description: value.description,
        price: value.price
    };
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startedAt: bigint;
    expiresAt: [] | [bigint];
    plan: _PlanType;
    updatedAt: bigint;
    state: _SubscriptionState;
}): {
    startedAt: bigint;
    expiresAt?: bigint;
    plan: PlanType;
    updatedAt: bigint;
    state: SubscriptionState;
} {
    return {
        startedAt: value.startedAt,
        expiresAt: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.expiresAt)),
        plan: from_candid_PlanType_n14(_uploadFile, _downloadFile, value.plan),
        updatedAt: value.updatedAt,
        state: from_candid_SubscriptionState_n16(_uploadFile, _downloadFile, value.state)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PostId;
    title: string;
    creator: Principal;
    contentType: {
        template: _TemplateId;
    } | {
        sticker: bigint;
    };
    createdAt: bigint;
    description: string;
}): {
    id: PostId;
    title: string;
    creator: Principal;
    contentType: {
        __kind__: "template";
        template: TemplateId;
    } | {
        __kind__: "sticker";
        sticker: bigint;
    };
    createdAt: bigint;
    description: string;
} {
    return {
        id: value.id,
        title: value.title,
        creator: value.creator,
        contentType: from_candid_variant_n7(_uploadFile, _downloadFile, value.contentType),
        createdAt: value.createdAt,
        description: value.description
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pro: null;
} | {
    creator: null;
} | {
    free: null;
}): PlanType {
    return "pro" in value ? PlanType.pro : "creator" in value ? PlanType.creator : "free" in value ? PlanType.free : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    canceled: null;
} | {
    expired: null;
}): SubscriptionState {
    return "active" in value ? SubscriptionState.active : "canceled" in value ? SubscriptionState.canceled : "expired" in value ? SubscriptionState.expired : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    template: _TemplateId;
} | {
    sticker: bigint;
}): {
    __kind__: "template";
    template: TemplateId;
} | {
    __kind__: "sticker";
    sticker: bigint;
} {
    return "template" in value ? {
        __kind__: "template",
        template: value.template
    } : "sticker" in value ? {
        __kind__: "sticker",
        sticker: value.sticker
    } : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CommunityPost>): Array<CommunityPost> {
    return value.map((x)=>from_candid_CommunityPost_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MarketplaceListing>): Array<MarketplaceListing> {
    return value.map((x)=>from_candid_MarketplaceListing_n9(_uploadFile, _downloadFile, x));
}
function to_candid_PlanType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanType): _PlanType {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionState_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionState): _SubscriptionState {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanType): {
    pro: null;
} | {
    creator: null;
} | {
    free: null;
} {
    return value == PlanType.pro ? {
        pro: null
    } : value == PlanType.creator ? {
        creator: null
    } : value == PlanType.free ? {
        free: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionState): {
    active: null;
} | {
    canceled: null;
} | {
    expired: null;
} {
    return value == SubscriptionState.active ? {
        active: null
    } : value == SubscriptionState.canceled ? {
        canceled: null
    } : value == SubscriptionState.expired ? {
        expired: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "template";
    template: TemplateId;
} | {
    __kind__: "sticker";
    sticker: bigint;
}): {
    template: _TemplateId;
} | {
    sticker: bigint;
} {
    return value.__kind__ === "template" ? {
        template: value.template
    } : value.__kind__ === "sticker" ? {
        sticker: value.sticker
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
